apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: elastic-system
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: elastic-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: elastic-system
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        # stand 10.08.2020
        image: fluent/fluentd-kubernetes-daemonset:v1.11.2-debian-elasticsearch7-1.0
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: quickstart-es-http
          # default user
          - name:  FLUENT_ELASTICSEARCH_USER
            value: elastic
          # is already present from the elasticsearch deployment
          - name:  FLUENT_ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quickstart-es-elastic-user
                key: elastic
          # elasticsearch standard port
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          # der elastic operator ist https standard
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "https"
          # dont need systemd logs for now
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          # da certs self signt sind muss verify disabled werden
          - name:  FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "false"
          # to avoid issue https://github.com/uken/fluent-plugin-elasticsearch/issues/525
          - name:  FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS
            value: "false"
          # for better separetion in kibana dashboards
          - name:  FLUENT_ELASTICSEARCH_INDEX_NAME
            value: fluentd
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config-vol
          mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config-vol
        configMap:
          # holds the different fluendt configuration files
          name: fluentd-config